const {_electron:electron}=require('playwright');
const {expect}=require('playwright/test');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'../..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'jarvis-planner-'));let app;
try{const env={...process.env,JARVISS_DATA:data,JARVISS_APP_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
app=await electron.launch({args:[path.join(root,'electron')],env});const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.waitForFunction(()=>document.querySelector('#status').textContent==='Model off');await page.locator('#setup-later').click();
const mediumDate=(y,m,d)=>page.evaluate(([y,m,d])=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(y,m-1,d)),[y,m,d]);
assert.equal(await page.locator('[name="lat"], [name="lon"]').count(),0);
await page.locator('[data-page="assistant"]').click();await page.locator('#situation-editor summary').click();await page.locator('[name="location_text"]').fill('123 Congress Ave, Austin, TX');await page.locator('#situation-find').click();
await page.locator('#atlas.visible').waitFor();assert.equal(await page.locator('#atlas').isVisible(),true);assert.equal(await page.locator('#city-search').inputValue(),'Austin, TX');assert.equal(await page.locator('#landmark-search').inputValue(),'123 Congress Ave');
assert.equal(await page.evaluate(async()=>(await window.jarviss.command('state')).profile.lat),'');
await page.locator('[data-page="plan"]').click();
async function tab(name){await page.locator('#plan-tabs button').filter({hasText:new RegExp('^'+name+'$')}).click();}
async function add(values){for(const [key,value] of Object.entries(values)){const input=page.locator('#plan-form [name="'+key+'"]');if(await input.evaluate(e=>e.tagName)==='SELECT')await input.selectOption(value);else await input.fill(String(value));}await page.locator('#plan-form button[type="submit"]').click();await page.waitForFunction(name=>[...document.querySelectorAll('#plan-list .plan-record strong')].some(e=>e.textContent===name),values.name).catch(async e=>{console.error('Plan failure:',await page.locator('#error').textContent(),await page.locator('#plan-form').innerText(),await page.locator('#plan-form').evaluate(f=>Object.fromEntries(new FormData(f))));throw e;});}
await add({name:'Water',quantity:30,unit:'liters',daily:10,notes:'Blue jugs in the garage'});await page.waitForFunction(()=>document.querySelector('#plan-list').textContent.includes('About 3 days left'));
assert.equal(await page.locator('#plan-list .record-meta.desc').innerText(),'30 liters · 10 a day · Blue jugs in the garage','One plain meta sentence per record');assert.equal(await page.locator('#plan-list .record-note.warn').count(),1,'Three days or fewer warns');
await page.locator('#plan-list button').filter({hasText:'Edit'}).click();await page.locator('#plan-form [name="quantity"]').fill('20');await page.locator('#plan-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#plan-list').textContent.includes('About 2 days left'));
await tab('Today');await add({name:'Paint storage shelf',priority:'Later'});await add({name:'Collect safe water',priority:'Now',owner:'Alex',needs:'Clean containers',due:'2026-09-16',check:'2026-09-17'});
await page.waitForFunction(()=>document.querySelector('#plan-list .plan-record strong').textContent==='Collect safe water');
await tab('Power');await add({name:'Radio',watts:12,hours:2});for(const [k,v] of Object.entries({battery_wh:120,solar_watts:20,sun_hours:3,efficiency:80}))await page.locator('#energy-form [name="'+k+'"]').fill(String(v));await page.locator('#energy-form button').click();await page.waitForFunction(()=>/Battery alone\s*5 days/.test(document.querySelector('#power-summary').textContent));
await tab('Garden');await add({name:'Beans',quantity:20,plant_on:'2026-05-01',days:60,next_check:'2026-05-08',notes:'South bed'});await page.waitForFunction(text=>document.querySelector('#plan-list').textContent.includes(text),`Harvest around ${await mediumDate(2026,6,30)}`);
await tab('People');await add({name:'Alex',skills:'Bicycle repair',needs:'Water',responsibility:'Repair pump',contact:'Library at noon'});
await tab('Log');await add({name:'Bridge damaged',status:'Reported',observer:'Neighbor',place:'River road'});assert.match(await page.locator('#plan-list').innerText(),/Reported/);
await tab('Group messages');await page.locator('#board-form [name="name"]').fill('Alex');await page.locator('#board-form [name="text"]').fill('Meet at the library at noon.');await page.locator('#board-form button').click();await page.waitForFunction(()=>document.querySelector('#board-messages').textContent.includes('Meet at the library'));
assert.equal(await page.locator('#board-messages time').last().innerText(),'just now','Board times read relative to now');assert.match(await page.locator('#board-messages time').last().getAttribute('datetime'),/^\d{4}-\d{2}-\d{2}T/);
await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent==='Model off');await page.locator('#setup-later').click();await page.locator('[data-page="plan"]').click();assert.match(await page.locator('#plan-list').innerText(),/About 2 days left/);
await page.locator('[data-page="docs"]').click();assert.equal(await page.locator('#guides details').count(),16);await page.locator('.recovery-entry summary').click();const recovery=await page.locator('#recovery-document').innerText();assert.ok(recovery.split(/\s+/).length<150);
await page.locator('#paste-document').click();await page.locator('#note-form [name="title"]').fill('Pump TP1 manual');await page.locator('#note-form [name="text"]').fill('E04: Intake obstruction. Switch off and check the filter.');await page.locator('#note-form button').filter({hasText:'Save document'}).click();await page.waitForFunction(()=>document.querySelector('#documents').textContent.includes('Pump TP1 manual'));
await page.locator('#docs-search').fill('pump tp1');await expect(page.locator('#reference-results .doc-row.mine:visible')).toHaveCount(1);assert.equal(await page.locator('#guides .doc-entry:visible').count(),0);
await page.locator('#reference-results .doc-row.mine .doc-row-main').click();await page.locator('#reference-reader.visible').waitFor();assert.match(await page.locator('#reference-text').innerText(),/Intake obstruction/);await page.locator('#reference-back').click();await page.locator('#docs-search').fill('');
await page.locator('#guides details').filter({hasText:'Make supplies last'}).locator('summary').click();await page.locator('#guides details').filter({hasText:'Make supplies last'}).getByRole('button',{name:'Open Supplies'}).click();assert.equal(await page.locator('#plan').isVisible(),true);
await page.locator('#plan-ask').click();assert.match(await page.locator('#question').inputValue(),/saved supplies/);
await page.locator('[data-page="plan"]').click();await page.screenshot({path:path.join(data,'planner.png')});
assert.deepEqual(errors,[]);console.log('PASS: no coordinate fields; street/address discovery without assumed position; supply edits; daily priorities; power budget; garden dates; people; evidence labels; messages; restart persistence; short guides; direct actions');
// Tabs follow the APG pattern; records re-render in place; Remove asks first; the board counts unread arrivals and copies its address.
const focused=()=>page.evaluate(()=>{const el=document.activeElement;return {id:el.id,text:el.textContent,action:el.dataset.action,card:el.closest('.plan-record')?.dataset.id};});
await tab('Supplies');assert.equal(await page.locator('#plan-tabs [role=tab][tabindex="0"]').count(),1,'One tab in the tab sequence');
await page.locator('#plan-tab-supplies').focus();await page.keyboard.press('ArrowRight');
assert.equal((await focused()).id,'plan-tab-tasks');assert.equal(await page.locator('#plan-tab-tasks').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#plan-title').innerText(),'Today');
await page.keyboard.press('End');assert.equal((await focused()).id,'plan-messages-tab');assert.equal(await page.locator('#board-panel').isVisible(),true);assert.equal(await page.locator('#plan-records').isVisible(),false);
await page.keyboard.press('ArrowRight');assert.equal((await focused()).id,'plan-tab-supplies','Arrow keys wrap');assert.equal(await page.locator('#plan-records').isVisible(),true);assert.equal(await page.locator('#board-panel').isVisible(),false);
await page.keyboard.press('Home');assert.equal((await focused()).id,'plan-tab-supplies');
assert.equal(await page.locator('#plan-tab-supplies').getAttribute('aria-controls'),'plan-records');assert.equal(await page.locator('#plan-records').getAttribute('aria-labelledby'),'plan-tab-supplies');
await tab('Today');const water=page.locator('#plan-list .plan-record').filter({hasText:'Collect safe water'});
await water.getByRole('button',{name:'Done',exact:true}).click();await water.getByRole('button',{name:'Reopen',exact:true}).waitFor();
assert.deepEqual(await focused().then(f=>[f.action,f.text]),['done','Reopen'],'Done re-renders the record in place and keeps focus');
await water.getByRole('button',{name:'Reopen',exact:true}).click();await water.getByRole('button',{name:'Done',exact:true}).waitFor();assert.equal((await focused()).action,'done');
const waterId=await water.getAttribute('data-id');await page.evaluate(()=>refresh());await page.waitForTimeout(100);
assert.equal(await water.getAttribute('data-id'),waterId);assert.equal((await focused()).card,waterId,'A background refresh keeps focus in the same record');
await water.getByRole('button',{name:'Edit',exact:true}).click();assert.equal((await focused()).id,'',);assert.equal(await page.locator('#plan-form [name="name"]').inputValue(),'Collect safe water');
await page.locator('#plan-form [name="owner"]').fill('Sam');await page.locator('#plan-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#plan-list').textContent.includes('Now · Sam · Due '));
assert.deepEqual(await focused().then(f=>[f.action,f.card]),['edit',waterId],'Saving an edit returns focus to that record');
await page.locator('#plan-form [name="name"]').fill('Check the roof');await page.locator('#plan-form [name="name"]').press('Enter');await page.locator('#plan-list .plan-record').filter({hasText:'Check the roof'}).waitFor();
assert.equal(await page.locator('#plan-form [name="name"]').evaluate(el=>el===document.activeElement&&el.value===''),true,'Add clears the form and focuses its first field');
const shelf=page.locator('#plan-list .plan-record').filter({hasText:'Paint storage shelf'});await shelf.getByRole('button',{name:'Remove',exact:true}).click();
await expect(shelf.locator('.confirm')).toContainText('Remove?');await shelf.locator('.confirm').getByRole('button',{name:'No',exact:true}).click();
assert.equal(await shelf.count(),1);assert.deepEqual(await focused().then(f=>[f.action,f.text]),['remove','Remove']);
await shelf.getByRole('button',{name:'Remove',exact:true}).click();await shelf.locator('.confirm').getByRole('button',{name:'Yes',exact:true}).click();await expect(shelf).toHaveCount(0);
assert.equal((await focused()).action,'remove','Focus moves to the next record after a removal');
await tab('Power');assert.equal(await page.locator('#power-summary div').count(),4);assert.equal(await page.locator('#power-summary dt').first().innerText(),'Daily use');
await tab('Garden');const beans=page.locator('#plan-list .plan-record').filter({hasText:'Beans'});await beans.getByRole('button',{name:'Remove',exact:true}).click();await beans.locator('.confirm').getByRole('button',{name:'Yes',exact:true}).click();
await expect(page.locator('#plan-list .empty')).toContainText('Nothing added yet.');await page.locator('#plan-list .empty').getByRole('button',{name:'Add your first crop'}).click();assert.equal(await page.locator('#plan-form [name="name"]').evaluate(el=>el===document.activeElement),true);
await tab('Group messages');assert.equal(await page.locator('#board-unread').isVisible(),false);assert.equal(await page.locator('#board-messages').getAttribute('role'),'log');
await page.evaluate(()=>{document.querySelector('#board-messages article').dataset.marker='kept';});await page.evaluate(()=>refresh());await page.waitForTimeout(100);
assert.equal(await page.locator('#board-messages article[data-marker="kept"]').count(),1,'Board messages are appended, never rebuilt');
await page.locator('#board-toggle').click();await page.waitForTimeout(300);
const board=await page.evaluate(()=>window.jarviss.command('board_state'));
if(board.active){
 await expect(page.locator('#board-address')).toHaveText(board.address);assert.equal(await page.locator('#board-code').innerText(),board.code);
 await page.locator('#board-messages').evaluate(el=>el.dataset.marker='same');await page.evaluate(()=>window.pollBoard());assert.equal(await page.locator('#board-messages[data-marker="same"]').count(),1);
 await page.locator('#copy-board-address').click();await expect(page.locator('#toast')).toHaveText('Address copied');
 assert.equal(await app.evaluate(({clipboard})=>clipboard.readText()),board.address);
 await tab('Supplies');
 const unread=await page.evaluate(async()=>{await window.jarviss.command('board_send',{name:'Sam',text:'Bringing water.'});await window.pollBoard();const badge=document.querySelector('#board-unread');return [badge.textContent,badge.hidden,document.querySelector('#plan-messages-tab').textContent];});
 assert.deepEqual(unread,['1',false,'Group messages1'],'A message received while the tab is hidden shows as unread');
 await page.locator('#plan-messages-tab').click();assert.equal(await page.locator('#board-unread').isVisible(),false,'Opening the tab clears the unread count');
 assert.equal(await page.locator('#board-messages article').count(),2);assert.equal(await page.locator('#board-messages article[data-marker="kept"]').count(),1);
 await page.locator('#board-toggle').click();await expect(page.locator('#board-panel .confirm')).toContainText('Stop the board?');
 await page.locator('#board-panel .confirm').getByRole('button',{name:'No',exact:true}).click();assert.equal(await page.locator('#board-toggle').innerText(),'Stop local board');
 await page.locator('#board-toggle').click();await page.locator('#board-panel .confirm').getByRole('button',{name:'Yes',exact:true}).click();
 await expect(page.locator('#board-toggle')).toHaveText('Start local board');assert.equal(await page.locator('#board-live').isVisible(),false);assert.equal((await focused()).id,'board-toggle');
 console.log('PASS board: stable address and code, copy to clipboard, unread badge, two-step stop');
}else console.log('SKIP board start/copy/unread/stop: no private LAN address on this machine');
assert.deepEqual(errors,[]);console.log('PASS: APG plan tabs, in-place record re-render with focus kept, two-step remove, empty state action, power stat row, unread badge and append-only board');
}finally{if(app)await app.close();fs.rmSync(data,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
